version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
      - dependency-name: '@typescript/native'
        update-types:
          - version-update:semver-major
      - dependency-name: eslint
        update-types:
          - version-update:semver-major
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
